### ISSUE TITLE
SQLContractedFlow has no planToSQLFlow method

### ISSUE THREAD

**Issue by melin** [maropu/spark-sql-flow-plugin#4]
SQLContractedFlow has no planToSQLFlow method，How to obtain the compressed Lineage data directly from optimizedPlan?

**Comment by maropu** [comment]
Yea, nice catch. I'll work on this.

**Comment by maropu** [comment]
Fixed in https://github.com/maropu/spark-sql-flow-plugin/commit/b5c1b6e57585d353bd2ed32da4014e551eb23ce9

**Comment by maropu** [comment]
https://github.com/maropu/spark-sql-flow-plugin/blob/b5c1b6e57585d353bd2ed32da4014e551eb23ce9/src/main/scala/org/apache/spark/sql/SQLFlow.scala#L803-L820
